install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'), repos='https://cloud.r-project.org/')
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
install.packages('C50', repos='https://cloud.r-project.org/')
install.packages('e1071', repos='https://cloud.r-project.org/')
install.packages('randomForest', repos='https://cloud.r-project.org/')
install.packages('nnet', repos='https://cloud.r-project.org/')
install.packages('RCurl', repos='https://cloud.r-project.org/')
install.packages('RJSONIO', repos='https://cloud.r-project.org/')
install.packages('sjmisc', repos='https://cloud.r-project.org/')
install.packages('pROC', repos='https://cloud.r-project.org/')
install.packages('rattle', repos='https://cloud.r-project.org/')
